# Generated by Django 5.0.2 on 2024-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('temperature_celsius', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('condition_text', models.CharField(max_length=100)),
                ('feels_like_celsius', models.FloatField()),
            ],
        ),
    ]
